trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "*"
pr:
  branches:
    include: 
      - main
  paths:
    include:
      - "*"

pool:
  vmImage: "ubuntu-18.04"

stages:
  - stage: "my_stage"
    displayName: "displayname for stage"
    jobs:
      - job: "my_job"
        displayName: "displayname for job"
        steps:
          - task: Bash@3
            displayName: "yolo display name"
            inputs:
              script: |
                echo "hello, world!"

