trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "*"
pr:
  branches:
    include: 
      - main
  paths:
    include:
      - "*"

pool:
  vmImage: "ubuntu-18.04"

stages:
  - stage: "yolo stage"
    jobs:
      - job:
        steps:
          - task: Bash@3
            displayName: "yolo bro"
            inputs:
              script: |
                echo "hello, world!"

